### ISSUE TITLE
デモ動画（s01_github_pr_issue_greeter）

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/github-app-sandbox#4]
https://github.com/user-attachments/assets/7ce109ec-3913-491f-9566-f488dd31e689

**Comment by iris-s-coon** [comment]
I.R.I.S Bot🤖が以下のラベルを提案し、適用しました：

- documentation
- question

**Comment by iris-s-coon** [comment]
このリポジトリは、GitHub App の開発、テスト、改善を安全に行うためのサンドボックスです。現在のリポジトリには、`README.md`と`issue_creator.log`の2つのファイルが含まれています。

このイシューは、デモ動画へのリクエストです。`README.md`には、「（デモ動画があればここに挿入）」という記述がありますが、まだ動画は存在しません。

このイシューに対して、以下のコメントを提案します。

---

このイシューは、デモ動画のリクエストですね。了解しました。

現在、リポジトリにはデモ動画はありません。

動画作成は、以下の手順で進めたいと思います。

1. **動画の目的を明確にする**: どのような内容のデモ動画にするか、ターゲットユーザー、伝えたいポイントなどを明確にします。
2. **動画の内容を企画する**: 動画のストーリーボードを作成し、具体的なシーンやセリフなどを検討します。
3. **動画を制作する**:  画面録画ツールや動画編集ソフトなどを使い、動画を制作します。
4. **動画を公開する**:  YouTubeなど、適切なプラットフォームに動画を公開します。
5. **README.md に動画へのリンクを追加**:  作成した動画へのリンクを `README.md` に追加します。

動画制作には、時間と労力を要します。できるだけ早く動画を制作し、公開できるように尽力します。

動画制作に関するご要望やご意見があれば、お気軽にお知らせください。
--- 

このコメントは、動画作成の計画を明確に示し、具体的な手順を提示しています。また、動画制作に関する要望や意見を募ることで、ユーザーとのコミュニケーションを促進しています。

動画の作成には時間がかかることを明確に伝えているため、ユーザーの期待値を調整し、過度な期待を避けることができます。

**Comment by iris-s-coon** [comment]
## 変更提案

```diff
--- a/README.md
+++ b/README.md
@@ -28,7 +28,7 @@
 
 ## 🌟 はじめに
 
-このリポジトリは、GitHub App 開発用のサンドボックスです。GitHub App の開発、テスト、改善を本番環境に影響を与えることなく安全に行うための環境を提供します。
+このリポジトリは、GitHub App 開発用のサンドボックスです。GitHub App の開発、テスト、改善を本番環境に影響を与えることなく安全に行うための環境を提供します。[デモ動画](https://github.com/user-attachments/assets/7ce109ec-3913-491f-9566-f488dd31e689)
 
 ## 🎥 デモ
 

```
